# site settings
title: Amplitude Systems
email: admin@goamplitude.com
description: Amplitude Systems helps businesses build decision-ready reporting systems and supporting infrastructure.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 5900 Balcones Drive
city: Austin
state: TX
zip_code: 78731
country: United States of America
phone: (512) 631-5123

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/jose-marquez89
  LinkedIn: https://www.linkedin.com/in/jose-marquez89

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md

destination: ./build
